name: 自动运行

on:
  workflow_dispatch:
  schedule:
    - cron: "0 22,9 * * *" # 每天运行 6:00, 17:00 两次 (UTC+8)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v2
      - name: 安装 python
        uses: actions/setup-python@v2
      - name: 安装依赖
        run: pip3 install -r requirements.txt
      - name: 设定时区
        uses: szenius/set-timezone@v1.0
        with:
          timezoneLinux: "Asia/Shanghai"
      - name: 运行
        env:
          DATA: ${{secrets.DATA}}
        run: python3 main.py
